### PR TITLE
Do not rely on arvatis/payone-php-api

### PR DESCRIPTION
**Pull request by Cruiser13**
Will not be installable due to weird symfony dependencies.

### CODE REVIEW

**Comment by Cruiser13** [comment]
@dpfaffenbauer would be great to see this merged and release tagged without other changes, should be working fine for coreshop 2.1 in this case.

**Comment by dpfaffenbauer** [comment]
sure, is done

**Comment by Cruiser13** [comment]
@dpfaffenbauer sorry to bother you - just noted that https://github.com/dpfaffenbauer/payone-php-api - while versioned properly - is not on packagist yet.

**Comment by dpfaffenbauer** [comment]
it is now, please check before next time

**Comment by Cruiser13** [comment]
> 
> 
> it is now, please check before next time

I'll, thanks and sorry!

**Pull request merged**
